version: "3.9"
services:
  app:
    container_name: app
    build: ./infra/php
    volumes:
      - ./src:/data
      - ../pipeStart:/hostpipeStart
      - ../pipeKill:/hostpipeKill
      - ./infra/supervisor/application.conf:/etc/supervisor/conf.d/laravel-worker.conf
      - ./infra/supervisor/supervisord.conf:/etc/supervisor/supervisord.conf
    restart: always

  web:
    container_name: web
    image: nginx:1.22.0
    ports:
      - 80:80
    volumes:
      - ./src:/data
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    restart: always
    working_dir: /data

  db:
    container_name: db
    build: ./infra/mysql
    volumes:
      - db-store:/var/lib/mysql
    restart: always

  # selenium:
  #   image: selenium/standalone-chrome-debug
  #   shm_size: '2gb' # 追加
  #   ports:
  #     - 4444:4444
  #     - 5900:5900
  #   depends_on:
  #     - web
  #   privileged: true

  # db-test:
  #   # container_name: db-test
  #   build: ./infra/mysql-test
  #   volumes:
  #     - db-store:/db-test/var/lib/mysql
  #   ports:
  #     - 3000:3306
  #   restart: always
 
volumes:
  db-store:
  
